mysteria/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('tools/company/', views.index, name='index'),
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include, re_path


urlpatterns = [
    path('tools/', include('tools.urls')),
    path('mysteria/', include('mysteria.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

tools/urls.py
from django.urls import re_path
from .views import main
from .views import idlescape

app_name = "tools"
urlpatterns = [
    re_path(r'^$', main.index, name='index'),
    re_path(r'^idlescape/$', idlescape.index, name="index"),
    re_path(r'^idlescape/enchant/augment/calculator$', idlescape.augment_calculator, name="augment_calculator")
]

mysteria/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

tools/models.py
from django.db import models

# Create your models here.

tools/forms.py
from django import forms


class AugChanceForm(forms.Form):
    Enchanting = forms.IntegerField(label='Enchanting', max_value=200, initial=99)
    Augment = forms.IntegerField(label='Augment', max_value=100, initial=5)
    Chance = forms.IntegerField(label='Chance', max_value=6, initial=6)
    Result = forms.CharField(label='Result', disabled=True, initial='87.53')

mysteria/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at Mysteria's house, please ring the door bell and wait patiently.")

polls/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

tools/views/idlescape.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from tools.forms import AugChanceForm
import math
from fractions import Fraction



def index(request):
    return HttpResponse("Hello, world. You're at the idlescape menu.")


def augment_calculator(request):
    if request.method == "POST":
        form = AugChanceForm(request.POST)
        if form.is_valid():
            form = form.cleaned_data
            L = form.get("Enchanting")
            a = form.get("Augment")
            c = form.get("Chance")
            chance = (math.pow((0.9 + Fraction(int(math.sqrt(L * 1.5)), 200)), a)*100)+c
            return JsonResponse({'Result': chance})
    else:
        form = AugChanceForm()
    return render(request, 'tools/idlescape/augment_calculator.html', {'form': form})

templates/base.html
{% comment %}


{% endcomment %}

<!doctype html>
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!-- Current language: {{ LANGUAGE_CODE }} -->
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <!-- meta  -->
    <meta charset="UTF-8">
    <meta name="robots" content="NONE,NOARCHIVE" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block meta%}{% endblock %}

    <!-- load fontawesome -->
    {# <link href='{% static "thirdparty/fontawesome-free-5.13.0-web/css/all.css" %}' rel="stylesheet"> <!--load all styles --> #}
    {# <script src="{% static 'fontawesome_free/js/all.min.js' %}"></script> #}
    <link href="{% static 'thirdparty/fontawesome-free-5.13.0-web/css/all.css' %}" rel="stylesheet" type="text/css">

    <!-- jquery -->
    <script src='{% static "thirdparty/js/jquery-3.4.1.min.js" %}'></script>
    <script src='{% static "thirdparty/jquery-ui-1.12.1/jquery-ui.min.js" %}'></script>
    <link rel="stylesheet" type="text/css" href='{% static "thirdparty/jquery-ui-1.12.1/jquery-ui.min.css" %}'>

    <!-- bootstrap -->
    <link rel="stylesheet" type="text/css" href='{% static "thirdparty/bootstrap-5.0.2-dist/css/bootstrap.min.css" %}'>

    <!-- tooltips  -->
    <link rel="stylesheet" type="text/css" href='{% static "thirdparty/css/tooltip.css" %}' />

    <!-- tablesorter  -->
    <script src={% static "thirdparty/tablesorter/jquery.tablesorter.min.js" %}></script>
    <script src={% static "thirdparty/tablesorter/jquery.tablesorter.widgets.js" %}></script>

    <!-- google charts -->
    <script src="https://www.gstatic.com/charts/loader.js"></script>

    <!--main js -->

    <!--main css -->


    <!-- local css -->
    {% block css%}{% endblock %}
    <!-- local js -->
    {% block jquery %}{% endblock %}

    <!-- tab -->
    <link rel="icon" href="/static/favicon.ico" type="image/x-icon">
    <title>Portfolio{% block title%}{% endblock%}</title>
</head>
<!--dark mode css -->
<body class="{% if request.session.dark %}dark{% endif %}">
  <div id="main-content" class="container-flex px-md-2 px-lg-3 px-xl-4" style="max-width: 1400px; margin: auto;">
    {% if not share %}
      <div id="header">
        {% include "header.html" %}
      </div>

      {% include "portfolio/section-message.html" %}
  {% else %}
    <div class="mb-3">

    </div>
  {% endif %}

    {% block content %}{% endblock %}

  </div>

  <script src='{% static "thirdparty/bootstrap-5.0.2-dist/js/bootstrap.bundle.js" %}'></script>

</body>
</html>

templates/header.html
{% comment %}
ui nav can go here - remember THIS ONE is all sites.
{% endcomment %}

templates/portfolio/section-message.html
{% comment %}
Copyright 2019 kivou.2000607@gmail.com

This file is part of yata.

    yata is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    any later version.

    yata is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with yata. If not, see <https://www.gnu.org/licenses/>.
{% endcomment %}


{% if sectionMessages|length %}
<div class="container-fluid p-md-3 p-1 mb-3 module rounded">
  {% for sm in sectionMessages %}
          <p class="mb-0">
            {% if sm.2 == "warning" %}
              <span title="Warning" class="warning" style="font-weight: bold;">
                <i class="fas fa-exclamation-triangle"></i>&nbsp;
            {% elif sm.2 == "error" %}
              <span title="Danger" class="error" style="font-weight: bold;">
                <i class="fas fa-radiation-alt"></i>&nbsp;
            {% else %}
              <span title="Notice" class="neutral" style="font-weight: bold;">
                <i class="fas fa-info-circle"></i>&nbsp;
            {% endif %}
            {{sm.0|title}}</span><span class="ms-2">{{sm.1|safe}}</span>
          </p>
  {% endfor %}
  </div>
{% endif %}

templates/tools/idlescape/augment_calculator.html
{% extends 'base.html' %}
{% load static %}
{% block title%}
    | Aug % chance
{% endblock %}
{% block content %}
{{ result }}
<div id="AugCalc">
    <form action="" method="post" id="AugChance">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" id="AugSubmit">
    </form>
</div>


<script>
$( "#AugChance" ).submit(function( event ) {
  event.preventDefault();
  console.log('is this thing on?')
    let posting = $.ajax({
            url: "",
            method: "POST",
            data: $("#AugChance").serialize(),
            headers:
            {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            datatype: "json"
        });
      posting.done(function( data ) {
          $('#id_Result').val(Number(Object.values(data)).toFixed(2));
  });
});
</script>
{{ Result }}
{% endblock %}